# Generated by Django 4.2.1 on 2023-05-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banermobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='images/project')),
                ('project_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_image', models.ImageField(upload_to='images/ProjectImage')),
                ('design_image', models.ImageField(upload_to='images/ProjectImage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
