# Generated by Django 4.2.1 on 2023-05-17 07:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_constructionimage_designimage_delete_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
