# Generated by Django 4.2.1 on 2023-05-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact_delete_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerbaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Offer Baner')),
            ],
        ),
    ]
