# Generated by Django 4.2.1 on 2023-06-06 07:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_youtuble'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_detail', ckeditor.fields.RichTextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packagename')),
            ],
        ),
    ]
