# Generated by Django 4.2.4 on 2023-09-27 11:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_youtubecategory_youtubeurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/image"),
                ),
                ("title", models.CharField(max_length=200)),
                ("content_sort", models.CharField(max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                ("date", models.DateTimeField()),
                ("author", models.CharField(max_length=100)),
                ("click_count", models.IntegerField(default=0)),
            ],
        ),
    ]
