# Generated by Django 4.2.4 on 2023-10-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackagePDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_pdf", models.FileField(upload_to="PackagePDF/")),
            ],
        ),
    ]
