# Generated by Django 4.2.4 on 2024-02-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_leads_packagepdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
